server:
  port: 8082
  
#info: 
#  app:  
#    name: "@project.name@" 
#    description: "@project.description@"  
#    version: "@project.version@"  
#    spring-boot-version: "@project.parent.version@"  

spring:
  application:
    name: battcn-manage
  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/  
    suffix: .html     
#  profiles: 
#    active: dev
  datasource:
    url: jdbc:mysql://192.168.18.183:3306/cloud_test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: xampp123%
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上  
      maximum-pool-size:  15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)  
      
mybatis:
  mapper-locations:
  - classpath:com/battcn/mapper/*.xml
  type-aliases-package: com.battcn.model
  configuration:
    map-underscore-to-camel-case: true

mapper:
  identity: MYSQL
  mappers:
  - com.battcn.framework.mybatis.mapper.BaseMapper
  not-empty: false
  
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true   



swagger:
  enable: true
  api-info:
    description: battcn-plus
    license: battcn-plus
    license-url: http://www.battcn.com
    terms-of-service-url: http://www.battcn.com
    title: 鏖战八方
    version: 2.5.1
    contact:
      email: 1837307557@qq.com
      name: Levin
      url: http://www.battcn.com
  docket:
    base-package: com.battcn.platform.controller
    group-name: battcn-manage  
  